### ISSUE TITLE
Bug: Supplie shuttle lost oxygen [discord]

### ISSUE THREAD

**Issue by gscrvs** [Carbonhell/Aliens-Colonialmarines#36]
I noted this bug time ago. Tbh, i dont know why.

**Comment by Carbonhell** [comment]
well if you open the door midtravel that happens,it's logical,although perhaps something to prevent griefers opening the shuttle and letting air out might be good

**Comment by Carbonhell** [comment]
Not a bug,maybe a lack of feature/"defense" against griffons rather
