### ISSUE TITLE
Bug: UGL has absolutely zero delay

### ISSUE THREAD

**Issue by MrJJJ2** [Carbonhell/Aliens-Colonialmarines#45]
[Note]: # M41A Rifle Underbarrel Grenade launcher has no delay, allowing you to spam it and kill most aliens easily with it
[Admins]: # Litteraly just grab it and turn it on, you don't even need to hold it with 2 hands, and click as fast as you can, boom

**Comment by Carbonhell** [comment]
Fixed in https://github.com/Carbonhell/Aliens-Colonialmarines/commit/5c17d31dfc426f1e5f589a0aafd05f349e4058c2
